### ISSUE TITLE
gnuplot is not exist in http://dl-3.alpinelinux.org/alpine/edge/testing/

### ISSUE THREAD

**Issue by jetgeng** [PeterGrace/opentsdb-docker#24]
when i build the image in my local computer . i get error as follow:

```
gnuplot(missing)
   required by : world[gnuplot]
```
then i check the repository ' http://dl-3.alpinelinux.org/alpine/edge/testing/ ' . i did not find the gunplot. but i found it in  http://dl-3.alpinelinux.org/alpine/edge/community/. 
so i change the line 12 of Dockerfile to 

```
    --repository http://dl-3.alpinelinux.org/alpine/edge/community/

```
and it was work!

**Comment by mesros** [comment]
Repository http://dl-3.alpinelinux.org/alpine/edge/community/ works  but gunplot does not. The following error is provided using the opentsdb gui:

[id: 0xf0fcfc58, /172.25.10.45:60085 => /172.17.0.2:4242] Bad Request on /q?start=2017/04/28-00:00:00&ignore=6&m=sum:IMEF01FA1148R%7Bapplication=asdp%7D&o=&yrange=%5B0:%5D&wxh=1900x779&style=linespoint&json: <pre>Gnuplot stderr:

set term png small size 1900,779
             ^
"/tmp/40313950.gnuplot", line 1: unrecognized terminal option

</pre>

**Comment by mesros** [comment]
Resolved using gnuplot 4.6 from  --repository http://dl-3.alpinelinux.org/alpine/v3.0/testing

**Comment by PeterGrace** [comment]
I'm updating the dockerfile to pull gnuplot from this repository.  Thanks for the suggestion @mesros!

**Comment by PeterGrace** [comment]
I'm reopening this since I used the repository as suggested by @mesros but still have the same gnuplot rendering error.  I'd like to figure out this issue but I don't want it to prevent my other updates to the repository, so I'll see about fixing it at a future point.

**Comment by jlferrer** [comment]
What seems to happen is that the gnuplot 5.x from Alpine does not has built-in support for terminal 'png', only supports 'pngcairo' which does not have the option to set the size:

- [Manual page for pngcairo version 5](http://gensoft.pasteur.fr/docs/gnuplot/5.0.4/node483.html)
- [Manual page for png version 5](http://gensoft.pasteur.fr/docs/gnuplot/5.0.4/node481.html)

The log from the gnuplot build that can be found [here](http://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/gnuplot/gnuplot-5.2.2-r1.log) shows that libgd-png based terminal is not integrated in gnuplot.

I tried to build locally and seems that `libwebp-dev` installation is missing for the configure script to enable the png terminal. 

As possible solutions, or the Alpine distro maintainers add the libwebp-dev as a dependency to build gnuplot or gnuplot has to be built from scratch in the Dockerfile.
